---
- name: Modify net.ipv4.tcp_tw_reuse
  sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: 1
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.ipv4.tcp_fin_timeout
  sysctl:
    name: net.ipv4.tcp_fin_timeout
    value: 30
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.ipv4.ip_local_port_range
  sysctl:
    name: net.ipv4.ip_local_port_range
    value: 2000 65535
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.ipv4.tcp_window_scaling
  sysctl:
    name: net.ipv4.tcp_window_scaling
    value: 1
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.ipv4.tcp_max_syn_backlog
  sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: 3240000
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.ipv4.tcp_max_tw_buckets
  sysctl:
    name: net.ipv4.tcp_max_tw_buckets
    value: 1440000
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.core.rmem_default
  sysctl:
    name: net.core.rmem_default
    value: "{{ ansible_memtotal_mb * 128 }}"
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.core.wmem_default
  sysctl:
    name: net.core.wmem_default
    value: "{{ ansible_memtotal_mb * 128 }}"
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.core.rmem_max
  sysctl:
    name: net.core.rmem_max
    value: "{{ ansible_memtotal_mb * 256 }}"
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.core.wmem_max
  sysctl:
    name: net.core.wmem_max
    value: "{{ ansible_memtotal_mb * 256 }}"
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.ipv4.tcp_mem
  sysctl:
    name: net.ipv4.tcp_mem
    value: "{{ (ansible_memtotal_mb * 256,ansible_memtotal_mb * 256,ansible_memtotal_mb * 256) | join(' ') }}"
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.ipv4.tcp_rmem
  sysctl:
    name: net.ipv4.tcp_rmem
    value: "{{ (ansible_memtotal_mb * 256,ansible_memtotal_mb * 256,ansible_memtotal_mb * 256) | join(' ') }}"
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.ipv4.tcp_wmem
  sysctl:
    name: net.ipv4.tcp_wmem
    value: "{{ (ansible_memtotal_mb * 256,ansible_memtotal_mb * 256,ansible_memtotal_mb * 256) | join(' ') }}"
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: yes
  become: yes

- name: Tuning soft of /etc/security/limits.conf
  pam_limits:
    domain: "*"
    limit_type: soft
    limit_item: nofile
    value: 200000
  become: yes

- name: Tuning hard of /etc/security/limits.conf
  pam_limits:
    domain: "*"
    limit_type: hard
    limit_item: nofile
    value: 300000
  become: yes

- name: Install the httpd rpm
  yum: name=httpd state=latest
  become: yes

- name: start the httpd service
  service: name=httpd state=started enabled=yes
  become: yes

- template: src=hello.j2 dest=/var/www/html/hello owner=root group=root mode=0644
  notify: restart httpd
  become: yes
