---
- name: Install the docker rpm
  yum: name=docker state=latest
  become: yes

- name: Install the docker-py pip
  pip: name=docker-py state=latest
  become: yes

- name: start the docker service
  service: name=docker state=started enabled=yes
  become: yes

- name: pull an image
  docker_image:
    name: zhenggu/haproxy
  notify: restart haproxy
  become: yes

- name: configure cert
  template: src=cert.j2 dest=/root/cert owner=root group=root mode=0644
  notify: restart haproxy
  become: yes

- name: configure haproxy
  template: src=haproxy.cfg.j2 dest=/root/haproxy.cfg owner=root group=root mode=0644
  notify: restart haproxy
  become: yes

- name: haproxy container
  docker_container:
    name: haproxy
    image: zhenggu/haproxy
    state: started
    volumes:
     - /root:/etc/haproxy
    published_ports:
     - 443:443
     - 80:80
     - 1993:1993
  become: yes
