---
- name: Modify net.ipv4.tcp_tw_reuse
  sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: 1
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.ipv4.tcp_fin_timeout
  sysctl:
    name: net.ipv4.tcp_fin_timeout
    value: 30
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.ipv4.ip_local_port_range
  sysctl:
    name: net.ipv4.ip_local_port_range
    value: 2000 65535
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.ipv4.tcp_window_scaling
  sysctl:
    name: net.ipv4.tcp_window_scaling
    value: 1
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.ipv4.tcp_max_syn_backlog
  sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: 3240000
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.ipv4.tcp_max_tw_buckets
  sysctl:
    name: net.ipv4.tcp_max_tw_buckets
    value: 1440000
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.core.rmem_default
  sysctl:
    name: net.core.rmem_default
    value: "{{ ansible_memtotal_mb * 128 }}"
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.core.wmem_default
  sysctl:
    name: net.core.wmem_default
    value: "{{ ansible_memtotal_mb * 128 }}"
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.core.rmem_max
  sysctl:
    name: net.core.rmem_max
    value: "{{ ansible_memtotal_mb * 256 }}"
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.core.wmem_max
  sysctl:
    name: net.core.wmem_max
    value: "{{ ansible_memtotal_mb * 256 }}"
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.ipv4.tcp_mem
  sysctl:
    name: net.ipv4.tcp_mem
    value: "{{ (ansible_memtotal_mb * 256,ansible_memtotal_mb * 256,ansible_memtotal_mb * 256) | join(' ') }}"
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.ipv4.tcp_rmem
  sysctl:
    name: net.ipv4.tcp_rmem
    value: "{{ (ansible_memtotal_mb * 256,ansible_memtotal_mb * 256,ansible_memtotal_mb * 256) | join(' ') }}"
    state: present
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Modify net.ipv4.tcp_wmem
  sysctl:
    name: net.ipv4.tcp_wmem
    value: "{{ (ansible_memtotal_mb * 256,ansible_memtotal_mb * 256,ansible_memtotal_mb * 256) | join(' ') }}"
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: yes
  become: yes

- name: Tuning soft of /etc/security/limits.conf
  pam_limits:
    domain: "*"
    limit_type: soft
    limit_item: nofile
    value: 200000
  become: yes

- name: Tuning hard of /etc/security/limits.conf
  pam_limits:
    domain: "*"
    limit_type: hard
    limit_item: nofile
    value: 300000
  become: yes

- name: Install the docker rpm
  yum: name=docker state=latest
  become: yes

- name: Install the docker-py pip
  pip: name=docker-py state=latest
  become: yes

- name: start the docker service
  service: name=docker state=started enabled=yes
  become: yes

- name: pull an image
  docker_image:
    name: zhenggu/haproxy
  notify: restart haproxy
  become: yes

- name: configure cert
  template: src=cert.j2 dest=/root/cert owner=root group=root mode=0644
  notify: restart haproxy
  become: yes

- name: configure haproxy
  template: src=haproxy.cfg.j2 dest=/root/haproxy.cfg owner=root group=root mode=0644
  notify: restart haproxy
  become: yes

- name: haproxy container
  docker_container:
    name: haproxy
    image: zhenggu/haproxy
    state: started
    volumes:
     - /root:/etc/haproxy
    published_ports:
     - 443:443
     - 80:80
     - 1993:1993
  become: yes
